/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./components/About.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Claim: typeof import('./components/Claim.vue')['default']
    Collection: typeof import('./components/Collection.vue')['default']
    CollectionCard: typeof import('./components/CollectionCard.vue')['default']
    HeaderMenu: typeof import('./components/HeaderMenu.vue')['default']
    HeroSplash: typeof import('./components/HeroSplash.vue')['default']
    Main: typeof import('./components/Main.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollDown: typeof import('./components/ScrollDown.vue')['default']
    ShoeSizes: typeof import('./components/ShoeSizes.vue')['default']
    Shop: typeof import('./components/Shop.vue')['default']
    Team: typeof import('./components/Team.vue')['default']
  }
}
